### ISSUE TITLE
Further URL bar options

### ISSUE THREAD

**Issue by razamattaz** [cadeyrn/newtaboverride#107]
I have a couple of suggestions that would assisst me greatly.

1. An option to place the cursor at the end of the URL bar on a new tab
2. Highlighting the entire URL within the new tab so that one can delete it quickly and type a new URL

Thank you for a useful addition to Firefox.

**Comment by cadeyrn** [comment]
Duplicate (of a lot of other issues!).

**Comment by razamattaz** [comment]
Sorry I did check the open issues and didn't believe they reflected what I wrote but I'll accept what you say!

**Comment by cadeyrn** [comment]
Most issues are closed because there is never more than one open ticket for one request. It's for WebExtensions neither possible to change the position of the cursor nor to highlight the entire URL. Maybe it will be possible in the future, but it's definitively not possible for Firefox 57 and Firefox 58. Mozilla has to implement this possibility in Firefox.

There is maybe a workaround to empty the address bar but this workaround won't work for all web sites and has other disadvantages. It's possible that an option will be included in a future update of New Tab Override.
