### ISSUE TITLE
Leaves A Blank Page In Recently Closed Tabs

### ISSUE THREAD

**Issue by Dypsis** [cadeyrn/newtaboverride#113]
New Tab Override works great apart from it leaving a blank page in Recently Closed Tabs.

**Comment by cadeyrn** [comment]
(only with the option to set the focus to the website instead of the address bar)

I don't see a way to prevent this because to set the focus to the website I have internally to create a new tab and close the current tab, so there is indeed a recently closed "blank" tab.

Unfortunately Mozilla has to provide a API for setting the focus so that New Tab Override's hacky solution is no longer necessary which causes this side effect.

If / once Mozilla will implement something better I will use the better solution. But for now I have to close the ticket because I can't do anything about it, sorry.

**Comment by Dypsis** [comment]
Hmmm! That's a real shame.
