### ISSUE TITLE
Close last tab then create home tab...

### ISSUE THREAD

**Issue by DennisHeimbigner** [cadeyrn/newtaboverride#115]
I have changed my about:config so that firefox will not exit
when last tab is closed. When I close that last tab,
a new tab is created as expected. However, I want this new
tab to open my home page. If, however, I create a new tab using the
'+' button, I do not want it open my home page.
Is this behavior possible to implement with your addon?

**Comment by cadeyrn** [comment]
Hi,

thank you for your suggestion. It's a very rare use case and you have to change a setting in about:config so I tend to mark this request as a WONTFIX because it would add a lot of complexity and I am not sure there are any other users interested in this option. But if other people say they also want this feature I can re-evaluate this.
