### ISSUE TITLE
about:home not working in Firefox 61

### ISSUE THREAD

**Issue by H0nzik1** [cadeyrn/newtaboverride#152]
about:home not working in Firefox 61
Thanks for fast fix!

**Comment by H0nzik1** [comment]
I need it, because another addon which I use for emails override new tab page (by unwanted custom page). I used your addon to override it back to the default. So why there is "about:home" in the list of option if it is not working? I thought you are that kind of developer who is pleased by reported issues, not one who is finding excuses that I dont need that feature working, etc.

**Comment by cadeyrn** [comment]
Firefox 61 has been released yesterday, I have a work and a private life. I will remove the option once I have time.

> I thought you are that kind of developer who is pleased by reported issues, not one who is finding excuses that I dont need that feature working, etc.

I don't know what was unclear for you when I said:

> There is no separate about:home in Firefox 61.

about:home and about:newtab are the same page, so there is nothing I can do.

**Comment by H0nzik1** [comment]
> I will remove the option once I have time.
So feature is not working, so it is easier to remove it than fix it. Good job.
If you are pissed and you dont have time for making addons for free, then dont do them. You will not be in rush then. Firefox 61 was released yesterday and I reported it today, so am I evil for you? Or am I good that I reported it fast?

> about:home and about:newtab are the same page, so there is nothing I can do.

And? How it is releated that it was working in Firefox 60, but is not currently working to Firefox 61? about:home  and about:newtab are same page, and? Just make default new tab option working in your addon, which is currently not. I already said you reason why I need to override new tab page to Firefox default......because another addon I use as side effect override it by unwanted page and I cannot disable it in that addon settings. 

Btw, I am not telling you to fix it now, fix it whenever you want....nobody is rushing you, I just reported it.

**Comment by cadeyrn** [comment]
> So feature is not working, so it is easier to remove it than fix it. Good job.

What is so difficult to understand for you that there is nothing I can do? Again: The old about:home no longer exists. There is no other option for me than removing the option. Why I have to repeat myself?

> If you are pissed and you dont have time for making addons for free, then dont do them.

![fp](https://user-images.githubusercontent.com/1100614/41992512-f590e64a-7a48-11e8-80f5-88bac905d5ec.jpg)

I have time for making add-ons for free, but I don't have time every day. I have a job, I am not a single, I have other important things to do, Firefox is not my life. So I shouldn't offer add-ons which are used by more than 130,000 users only because I can't address feedback within one day? What's wrong with you?

> And? How it is releated that it was working in Firefox 60, but is not currently working in Firefox 61? 

Is it really not to understand for you? There are differences between Firefox versions. Firefox 60 is Firefox 60 and Firefox 61 is Firefox 61.

Closing this issue because of your unkindliness.
