### ISSUE TITLE
Replace about:home by about:newtab - default new tab page is not working.

### ISSUE THREAD

**Issue by H0nzik1** [cadeyrn/newtaboverride#153]
Hello, 
since you answered at my last bug report and you posted many questions there and immediately you closed thread so I answer here. if you have explained it well, you said that about:home page was replaced  by page about:newtab in Firefox 61 which is probably Firefox new tab default address now. Change the address about:home to  about:newtab to make it working again? 
Is it so hard for you?

**Comment by cadeyrn** [comment]
This does not make sense at all. The only reason why people install this add-on is because they do *not* want to have about:newtab as new tab page. Why should there be a option to use about:newtab as new tab page if this is the default behaviour of Firefox without add-on? There is really no point in providing a "about:newtab" option.

**Comment by cadeyrn** [comment]
There were technical differences between about:home and about:newtab in previous version, that's why it was possible to set about:home as new tab page but not about:newtab via WebExtension. With Firefox 61 these differences no longer exists, about:home has been "fixed" and this means neither can be set as new tab page via WebExtensions. WebExtensions are not allowed to use privileged about: pages as new tab page. I already said there is nothing I can do but removing the option. I wouldn't write that if it wasn't true…

**Comment by H0nzik1** [comment]
Ok thanks, now explanation is clear. Can you make some easy substitution for default new tab page? I need just most visited pages in tiles like default new tab page. Thanks

**Comment by cool-charac** [comment]
I don't know about you guys, but Firefox without addons has always never been able to load about:home when I click on the new tab button.

**Comment by cadeyrn** [comment]
@H0nzik1: I don't understand the request, please provide more details: what exactly do you need? If you need "most visited pages in tiles like default new tab page" why not using the default new tab page?

**Comment by cadeyrn** [comment]
Could you please tell me which add-on for emails do you use? I have to test if I can provide a solution for Firefox 61+.

**Comment by H0nzik1** [comment]
> Could you please tell me which add-on for emails do you use? I have to test if I can provide a solution for Firefox 61+ because AFAIK only one add-on can control the new tab page.

It is in Czech language, so I am not sure if you understand it. You can add email accounts in addon settings and then you will get notification once emails comes, and by click on account you are loaded directly in message box of Seznam email without login. (Emails are at www.seznam.cz company which is most popular copany providing emails and many people including me use that page as default homepage in Czech Republic, it is also more popular than gmail)
https://www.seznam.cz/doplnky/?prohlizec=firefox

**Comment by cadeyrn** [comment]
Thanks, I'll test it as soon as I can. I have a lot to do at the moment because of an important customer project, which is why I also have to work on the weekends.

**Comment by H0nzik1** [comment]
> Thanks, I'll test it as soon as I can. I have a lot to do at the moment because of an important customer project, which is why I also have to work on the weekends.
Np, I dont hurry ;-)
