### ISSUE TITLE
extension override stopped working with Mail.com extension

### ISSUE THREAD

**Issue by mailcomuser** [cadeyrn/newtaboverride#155]
I have an extension from Mail.com that shows how many emails I have in the menu bar.  However, that extension also controls the new tab page in Firefox.  I installed your new tab override extension and it worked for a few weeks then stopped working.  I tried re-installing it, still doesn't work.  What am I doing wrong?

**Comment by cadeyrn** [comment]
What is your New Tab Override configuration, what's the expected new tab page and what the actual (wrong) new tab page?

**Comment by mailcomuser** [comment]
Hi,

 

The New Tab Overide is configured to "default homepage of Firefox (about:home)".  I expect it to go the homepage of Firefox.  The wrong tab is Mail.com search page.  I hope this helps.
 

Best Always,

Pat Torres
818-618-1385
pattorres@email.com

 
 

Sent: Sunday, July 01, 2018 at 12:45 AM

**Comment by cadeyrn** [comment]
There is no longer a "about:home" in Firefox. It was already the same as about:newtab but with a few internal differences. These differences are gone with Firefox 61, so about:home and about:newtab are really the same. This also means that, like about:newtab, about:home can't be set as new tab by WebExtensions. You don't need this add-on at all do use the default new tab page.

I will remove the option to use about:home with the next update of New Tab Override because it does not exist.

**Comment by mailcomuser** [comment]
I'm sorry, but I'm cofused.  How do I get the Firefox homepage to show up as a new tab, while still showing the Mail.com icon in the toolbar?
 

Best Always,

Pat Torres
818-618-1385
pattorres@email.com

 
 

Sent: Sunday, July 01, 2018 at 3:55 AM

**Comment by cadeyrn** [comment]
Please ask the developer of the mail.com add-on how you can use their add-on without their override. There is nothing I can do and it shouldn't be the job of an add-on to disable parts of another add-on. It's a coincidence that it's worked so far. It was never planned that about:home has a different behaviour than about:newtab in Firefox 57 and higher and it was already not possible in the past to use about:newtab as new tab page within a WebExtension. The differences are gone in Firefox 61, that's why I can't do anything.
