### ISSUE TITLE
Won't install on Firefox ESR

### ISSUE THREAD

**Issue by andrewbush** [cadeyrn/newtaboverride#163]
I have noticed the latest update now requires Firefox version 61 to install. 

Is there any way to allow it to install for Firefox ESR 60.1? 

Mozilla does not plan to update Firefox ESR past version 60 until next year so it would be great if this extension can continue to work with the ESR version until then.

I think it would be very helpful to allow this since many organizations use the ESR version.

**Comment by cadeyrn** [comment]
You can still use New Tab Override 13.0 on Firefox ESR 60. New Tab Override 14.0 only removed two options which are no longer useful since Firefox 61, added two new translations and improved three other translations.

I don't think there will be a lot of new features in New Tab Override in the next months, if any. And it would be comlicated to support both, Firefox 60 and newer versions of Firefox because the removed options cause problems in newer Firefox versions.

**Comment by davidhedlund** [comment]
The [planned](https://wiki.mozilla.org/Release_Management/Calendar) Firefox ESR 68.2 release date  is 22th October (3 months).

**Comment by davidhedlund** [comment]
Firefox ESR 61 will never be released, the [planned](https://wiki.mozilla.org/Release_Management/Calendar) Firefox ESR 68.2 release date  is 22th October 2019 (1 year and 3 months).

**Comment by davidhedlund** [comment]
@cadeyrn Can you announce that you won't make it compatible with Firefox ESR until it's next release that I described above?

**Comment by cadeyrn** [comment]
There will be no "Firefox ESR 61" but there *is* a "Firefox 61" and I have to support Firefox 61 and newer versions, especially because the big majority of users of New Tab Override does not use Firefox ESR but the mainstream version of Firefox. You can install New Tab Override 13 in Firefox ESR 60 at any time:

https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/versions/?page=1#version-13.0.0

I don't understand what exactly should be announced. New Tab Override 13 works in Firefox ESR 60 and there were zero new features in New Tab Override 14, only two removed options because they didn't work in Firefox 61 and because they are not needed in Firefox 61 and higher. Firefox 60 was not affected at all, so there is no need for users of Firefox ESR 60 to use New Tab Override 14, the changes were only relevant for Firefox 61 (well, there were also updated translations in New Tab Override 14, but I don't think that's a big deal).

I don't work on new features for New Tab Override at the moment because I think New Tab Override already has all features wanted by 99 percent of the users of this WebExtension. My primary focus are bugfixes and needed changes by Firefox updates and I am not aware of any bug affecting Firefox ESR 60.

It's possible that new features will be added to New Tab Override once there are new WebExtension APIs implemented by Mozilla which are interesting for New Tab Override but in this case it's not possible to implement these features for Firefox ESR 60 because Firefox ESR 60 won't have these APIs.

So I don't see what exactly should be made compatible with Firefox ESR 60.
