### ISSUE TITLE
NTO Intereferes with Tree Style Tab new tab placement, always at end of tabs instead

### ISSUE THREAD

**Issue by slaingod** [cadeyrn/newtaboverride#174]
NTO should honor other extensions placements in the order of tabs. In particular Tree Style Tab is a firefox extension that allows for nested tabs in a vertical list rather than horizontally at the top of the browser. 

This is what it should look like when I select the child tab and hit Ctrl-T.
![image](https://user-images.githubusercontent.com/17370539/50740046-51734000-11ae-11e9-8f45-8b2210a34a00.png)

This is what it looks like when NTO is enabled:
![image](https://user-images.githubusercontent.com/17370539/50740057-8da6a080-11ae-11e9-95c9-aa32c47f0f97.png)

**Comment by PixelEater** [comment]
I noticed something changed too. Previously all I needed to do in Tree Style Tab was set it to "guess" a new tab via about:blank. Now I had to go into about:config and toggle browser.tabs.insertAfterCurrent to true. I'm still not sure if this will replicate all the desired behavior we need it to. I'm trying to remember also, a while back there was a more technical url which referenced this extension than about:blank. The need for that may have been dropped altogether. Here's hoping for a real solution that doesn't require non-default options.

**Comment by cadeyrn** [comment]
I don't know how it should be possible for otheres add-ons to respect the grouping of Tree Style Tab. If you have a solution please let me know. For now I will close this issue because it's not actionable for me.

**Comment by stephan-dev** [comment]
I have the same problem. It's nice to find information here, even if closed as not possible.
A semi workaround, for TST users, when you want to open a new tab as close as possible to the current tab, is to avoid classic ways of opening a new tab (including Ctrl+T). Instead, right-click the label of the current tab in TST, and click "new tab".
For me at least, instead of opening the new tab at the end of the main tree, it's opened as sibling of current tab.
