### ISSUE TITLE
newtaboverride does not load current homepage

### ISSUE THREAD

**Issue by whyisntit** [cadeyrn/newtaboverride#221]
Instead it loads it's own newtaboverride page

**Comment by cadeyrn** [comment]
This is not a valid bug report. There are no information about the Firefox version, the version of New Tab Override or any steps to reproduce, including the URL that is not working. Please provide the missing information.

**Comment by retsuyama** [comment]
Same issue here using Firefox 80.0.1 (64-bit) and latest New Tab Override from AMO. In NTO setting if you set to current home page like this it'll automatically open new tab in NTO setting page. If you previously set in my case https://duckduckgo.com it'll work. But if you change it back to set to current home page, it'll stay redirect to previously set up link in custom URL. I'm not sure if it because the combination of add-ons i'm currently using since it's just Universal Bypass, HTTPS Everywhere and Ublock Origin.
![Screenshot 2020-09-12 083350](https://user-images.githubusercontent.com/17337588/92984276-4b7d4880-f4d3-11ea-83ef-d5c58a26d51f.png)
.

**Comment by cadeyrn** [comment]
I cannot reproduce, works without any problems for me with https://duckduckgo.com as homepage. Please test with a clean profile and only New Tab Override as only add-on to make sure that there no conflict with other add-ons.
