### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by siffegh** [cadeyrn/newtaboverride#245]
On my working FF profile (v88.0.1), I have options for 'Tab position' and 'Focus'. After installing on a new FF profile, I no longer see those options - ?

**Comment by cadeyrn** [comment]
I guess you have New Tab Override 15.0 installed on your working profile and New Tab Override 14.4 on your new profile because that's the latest version that is offered on addons.mozilla.org at the moment. Version 15.0 is temporarily disabled and will be re-published as version 15.1 very soon (it's already submitted and is awaiting the review).

**Comment by siffegh** [comment]
Yup, that explains it. Thanks!

**Comment by asdnet-tech** [comment]
Hi guys, any news on this one?

**Comment by cadeyrn** [comment]
The new version is still waiting for review.

**Comment by cadeyrn** [comment]
@siffegh @asdnet-tech New Tab Override 15.1 is available for download now.
