### ISSUE TITLE
Following latest Firefox update (90.0.2), New Tab Override is not working

### ISSUE THREAD

**Issue by Florio60** [cadeyrn/newtaboverride#251]
When I opened Firefox this morning, the browser had been updated to version 90.0.2, and my extensions were no longer visible. I closed Firefox, and when I opened it a few hours later, the extensions had returned, but had all been reset. New Tab Override is no longer working. I set it to Custom URL and have chosen https://www.google.com/ as the home page, but the page won't open in new tabs. Is there a particular problem with this latest version of Firefox?

**Comment by cadeyrn** [comment]
I cannot reproduce, New Tab Override still works as expected with Firefox 90.0.2. It's also confusing that you said that you set https://www.google.com/ as home page since New Tab Override changes the new tab page, not the home page. But even if you set it as home page and configured New Tab Override to use your home page as new tab page, it works for me.

You said that your extensioons were no longer visible so it seems that something is broken on your system and that it's not a bug of Firefox or New Tab Override.

**Comment by Florio60** [comment]
I've now got it working; it was a problem with Firefox settings. However, many thanks for your reply!!

**Comment by cadeyrn** [comment]
Glad that you was able to solve your issue!
