### ISSUE TITLE
user icon

### ISSUE THREAD

**Issue by abitawoods1** [cadeyrn/newtaboverride#260]
This is a minor issue, but would be nice to address:

I have a home page with my own favicon, which shows up via a link rel OR a body url, for use on my various browsers
FF will show off my own icon on the first new tab, but subsequent pages, loaded via NewTabOverride, use your icon.

Is there a way to segregate your icon from the DLL [like placing it in the addon folder ] so that your icon can be swapped for one of our own choosing ?

thanks for your efforts !

**Comment by Gerald4000** [comment]
Similar problem here.

This extension doesnt need its own icon.
Its one and only feature is emulating native browser behaviour.

A new tab doesnt have any icon.
So I find the current solution rather irritating.

Then also there are people like @abitawoods1 who would like to use their own custom favicon.

So, I too wish for an option to change this extensions behaviour.
Just in my case I would prefer to inactivate the icon completely, instead of changing it.

**Comment by FMRed** [comment]
Agree with both guys above. 
Standard FF icon will be fine too. But ofc custom icon even better option.
I'm using dark theme too and this icon looks kind a bad.

**Comment by cadeyrn** [comment]
I cannot reproduce.
