### ISSUE TITLE
Local file no more valid

### ISSUE THREAD

**Issue by YiffyC** [cadeyrn/newtaboverride#3]
In the lastest version local HTML files such as " /Users/me/Documents/index.html " are not valid anymore.

**Comment by cadeyrn** [comment]
As you can read in the release notes WebExtensions are not allowed to use local files as new tab page for security reasons. You have to upload your file to a web server. There is nothing what I can do as part of New Tab Override.

**Comment by hdmi** [comment]
I apologize for commenting in a closed issue. 
But I would like to know if this new restriction it is from the browser side or because you decided to not allow local files in the new version?

However, It is probably not big deal because as I've read in other issues now it is allowed to run the file in a local server like node or apache.

**Comment by cadeyrn** [comment]
> I apologize for commenting in a closed issue.

No problem. I closed the bug only for organizational reasons because there is nothing to implement. Comments are still allowed. ;)

> But I would like to know if this new restriction it is from the browser side or because you decided to not allow local files in the new version?

As I already said WebExtensions are not allowed to load local files and there is nothing what I can do. I would love to provide this feature but it's not possible and it won't be possible in a future update of Firefox.

> However, It is probably not big deal because as I've read in other issues now it is allowed to run the file in a local server like node or apache.

Yeah, that's the workaround on the user side. I hope it's good enough for you. It's probably a problem for some users…

**Comment by Drugoy** [comment]
Could you file a bug in bugzilla with the request to add new API(s) required to bring the feature back?

**Comment by cadeyrn** [comment]
> Could you file a bug in bugzilla with the request to add new API(s) required to bring the feature back?

No, there are already requests and it's denied for security reasons.

> p.s.: I had to revert back to v6.0.1 only because of that feature. Without this feature your add-on is useless to me.

That's no long term solution as Firefox 57 will *only* allow WebExtensions.

**Comment by yfdyh000** [comment]
> No, there are already requests and it's denied for security reasons.

Which? https://bugzilla.mozilla.org/show_bug.cgi?id=1266960 is open.

**Comment by cadeyrn** [comment]
well, it was denied for the mid term and there is no current activity regarding a long term solution.

It was made very clear that this restriction is intented and for security reasons. Not only in this ticket, also in an email conversation I had. In this conversation it was also confirmed that there is no workaround. Maybe there will be a solution at some point in the future. But it's an *maybe* and an *earliest in 2018*, it's completely out of scope for Firefox 56 and Firefox 57.

As this ticket already exists it makes no sense to open another ticket. I already expressed my opinion in this ticket.

**Comment by Drugoy** [comment]
> I already expressed my opinion in this ticket.
Thank you. We need that if we want Firefox stay an extensible browser. If it mutates into a chrome-like poorly extensible crap - I'll just stop using it. I'm a power user, I don't care whether 99% of users need this feature or not: I do.

**Comment by cadeyrn** [comment]
> If it mutates into a chrome-like poorly extensible crap

That's not the case. Firefox is much more powerpul than Chrome as you can see, for example, in this comment from Gorhill, developer of uBlock Origin:

https://discourse.mozilla.org/t/support-ublock-origin/6746/451?u=ghm113

I really like WebExtensions, it's a great architecture for add-ons. The problem is that some important features are still missing…

**Comment by Drugoy** [comment]
> That's not the case.

This is exactly the case. I don't buy onto anyone's bullshit, I trust the experience.
@gorhill says:
> chromium-based browsers don't support userstyles

<a href="https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe">B/s</a> + at the same time Mozilla first abandons DOM Inspector and then they forbid Developers Tools Inspector inspect chrome of the browser and then they broke APIs so hard that DOMi stopped working on the latest Nightly.
How is one supposed to write styles for the browser without an inspector?
> Chromium-based browsers are being “infested” by Instart Logic tech10,2k which works around blockers and worst, around browser privacy settings

Firefox is infested with their spyware (non-optional stealthy telemetry), <a href="https://github.com/mozilla/addons-frontend/issues/2785">spyware by Google that one can't even turn off because mozilla hardcoded mozilla.org and add-ons manager into the whitelist</a> and bloatware.

> I really like WebExtensions, it's a great architecture for add-ons.

The problem is that it being shoved into our faces. There was no need to cut away XUL and APIs before implementing all of the functionality as WebExtension APIs.
Mozilla declared war on power users of Firefox.

**Comment by gorhill** [comment]
@Drugoy 

> B/s

Stylish/Chromium does not use user styles -- these do not exist on Chromium-based browsers:

- <https://bugs.chromium.org/p/chromium/issues/detail?id=347016>
- <https://bugs.chromium.org/p/chromium/issues/detail?id=632009>

**Comment by cadeyrn** [comment]
> I don't buy onto anyone's bullshit, I trust the experience

It's not "anyone's bullshit", it's a statement of a very experienced add-on developer and it's a fact. It's great that you have experience but with regards to add-ons you should trust the developers of add-ons.

> at the same time Mozilla first abandons DOM Inspector and then they forbid Developers Tools Inspector inspect chrome of the browser and then they broke APIs so hard that DOMi stopped working on the latest Nightly.

Nonsense. 1. DOMi is not a Mozilla project, it's a project of the SeaMonkey Council. 2. Inspecting the browser chrome of Firefox works great with Firefox dev tools.

> How is one supposed to write styles for the browser without an inspector?

There is an inspector: https://youtu.be/cjwL4mVJSj8

> Firefox is infested with their spyware

Nonsense.

> mozilla hardcoded mozilla.org and add-ons manager into the […] bloatware.

Nonsense.

> There was no need to cut away XUL and APIs before implementing all of the functionality as WebExtension APIs.

There was and there is a need. The fact that you don't know anything about it does not mean there is no need.

> Mozilla declared war on power users of Firefox.

Nonsense.

First and last warning: stop trolling on my repository, otherwise I'll delete your comments. It's an issues tracker for my add-on, it's no place for bashing against Mozilla.

**Comment by Drugoy** [comment]
> Stylish/Chromium does not use user styles -- these do not exist on Chromium-based browsers:

What does Stylish do? Provides a way to apply a user style to the page and/or chrome. Stylish on Chromium-based browsers works this way too. The order in which the browser allows an extension apply the styles - it's details.

@cadeyrn,
message received.

**Comment by cadeyrn** [comment]
New Tab Override shipped with a new local file option. It's not perfect but it's the best possible solution.

**Comment by Drugoy** [comment]
For the curious ones - it's not fully functional, it ignores all included files except the single target html file.
The last non-broken version is 6.0.1 and it can be found <a href="https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/versions/">here</a>.

**Comment by cadeyrn** [comment]
> For the curious ones - it's not fully functional, it ignores all included files except the single target html file.

… as you can read on the options page. There is a description explaining the restrictions.

> The last non-broken version is 6.0.1 and it can be found here.

It's not "broken", it's all what is possible for WebExtensions. By the way, using a local host is super easy and has *no* restrictions. People should better do that than using the local file option. ;)

**Comment by Drugoy** [comment]
> By the way, using a local host is super easy and has no restrictions. People should better do that than using the local file option. ;)

Yeah, right, just to make a browser be able to open my homepage on each new tab I'm going to set up a webserver to serve that page locally. In an ill mind it makes so much more sense than pushing degrading f---ers to provide necessary APIs.

**Comment by cadeyrn** [comment]
Sorry, but you have all the tools, you just have to use it. It's easy and no problem. If it's not good enough for you (for whatever reason), please ask Mozilla for another solution, the issues tracker of New Tab Override is not the right place.
