### ISSUE TITLE
Yes, you can use Superstart extension

### ISSUE THREAD

**Issue by casteldaccia** [cadeyrn/newtaboverride#31]
Hi,

I open a new thread because those related to the topic are closed and I think this can help. In order to use Superstart extension, you can go to **about:config**, look for **extensions.superstart.enable.searchengine.select** and change the valor to **true**. This way, you can make work your about:superstart custom url despite the http://. It works for me. I guess this applies to other extensions.

Regards.

**Comment by cadeyrn** [comment]
Thank you for your advice.

> I open a new thread because those related to the topic are closed

I have to close all tickets which are either done or not actionable because it's an issue tracker and I have to keep track of open issues. So I closed this issue, too. It does not mean that no other comments are allowed, it only means that the ticket contains nothing to fix or to implement for me.
