### ISSUE TITLE
Unable to open extension urls, `moz-extenstion` protocol

### ISSUE THREAD

**Issue by amithm7** [cadeyrn/newtaboverride#310]
I'm trying to open extension url like this:

```
moz-extension://3b12022a-75a7-4189-8431-a45b8c5ff24e/popup/index.html#inTab
```

But this url get's converted to an `http` protocol url automatically.

```
https://moz-extension//3b12022a-75a7-4189-8431-a45b8c5ff24e/popup/index.html#inTab
```

**Comment by AndydeCleyre** [comment]
I just installed this extension for the purpose of setting new tab to a `moz-extension://` URI, FWIW. Thanks @amithm7 for not only reporting this but submitting the PR.

**Comment by cadeyrn** [comment]
Thank you for the report and the pull request. In the past it was not possible to use moz-extension URIs as new tab page. I will check if this works now but it will take a few more days because I am very busy with other high priority projects right now. I just didn't want to keep you waiting any longer without feedback.

**Comment by clach04** [comment]
@amithm7 does this allow data payloads that are base64 encoded?

    data:text/html;base64,....

Is so this would solve the use case I'd like which is to spin up a page with html without hitting a web server (local files are not allowed in the extension apparently).

**Comment by amithm7** [comment]
@clach04 No, the PR I opened doesn't consider `data:` URI's. Only protocols of the form `protocol://`, does it consider to be excluded from automatically adding `http://`.
