### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by ernst12345** [cadeyrn/newtaboverride#32]
windows 7 64 bit professional
Firefox 55.0.3 (32-bit)
Newtab: got forced an update for Newtab. Result: no tiles anymore, no gear icon. Unable to 
restore to previous version.  Unable to use the solutions provided. I want the tiles back.
Any other help than changing from Firefox to an other browser?

**Comment by jscher2000** [comment]
If you want to use the built-in **about:newtab** page, that might be an option or you can simply remove the New Tab Override extension and let the built-in page take over.

If some OTHER unwanted page appears after that, it could be caused by one of your other extensions. But this is better resolved on a support site like https://support.mozilla.org/questions/new/desktop/fix-problems

**Comment by cadeyrn** [comment]
If I want to use the original new tab page I don't install an add-on to change the new tab page to something different, it does not make sense at all. And my add-on provides an option for the default new tab page where you can read that you have to disable or to uninstall the add-on to use the original new tab page. Users of add-ons should read the descriptions before complaining…

**Comment by ScalaAccaZero** [comment]
Windows 7 Professional
I configure New Tab Override with new tab page= https://www.google.it/
but it does not work( everything goes as if I didn't configure anything
In Windows 10 everything goes OK.
Help, help, help

**Comment by cadeyrn** [comment]
Please don't hijack old and unrelated issues. Open a new issue and provide more information in your new issue: Firefox version, New Tab Override version, exact steps to reproduce.
