### ISSUE TITLE
Never Opens In Custom URL With Toolbar

### ISSUE THREAD

**Issue by tunescool2** [cadeyrn/newtaboverride#322]
when i use the tab bar the url will open google. but i mostly use the toolbar icon and i just want to see shiny google there but its never there, for years

![Screenshot 2023-08-31 at 3 12 53 AM](https://github.com/cadeyrn/newtaboverride/assets/141515519/1a91e94f-2756-496e-82fc-4bb4dca122b4)

**Comment by cadeyrn** [comment]
> but i mostly use the toolbar icon and i just want to see shiny google there but its never there, for years

I don't understand that part. Can you please provide detailled steps to reproduce? Thank you.

**Comment by tunescool2** [comment]
its plain english anyone can understand

**Comment by tunescool2** [comment]
the new tab button is supposed to go to the address i want it to, which is google. instead it goes to the image i posted avove

**Comment by cadeyrn** [comment]
Which button? I can't see the "new tab button" in your screenhot.

**Comment by cadeyrn** [comment]
> i dont like the look of firefox's button, so i use this add-on

That's not what this add-on is for at all. If you want to change the look of buttons, you can do that with the userChrome.css file.

>  just takes me to preferences which i can do easily by going to preferences itself?

If that's really your argument, you don't need this add-on either, because you can just use Firefox' button to open a new tab.

Without this button you would have to find the add-on's settings via about:addons and that's not obvious to all users.

> its plain english anyone can understand […] which everyone on the planet recognizes as add […] who's idea was that

You should really watch your tone. The way you talk to me is not okay.
