### ISSUE TITLE
"Access to local files via URL is no longer possible due to Firefox restrictions"

### ISSUE THREAD

**Issue by Angolmagyar** [cadeyrn/newtaboverride#33]
"Access to local files via URL is no longer possible due to Firefox restrictions" is not at all true. I have firefox 55.0.3 (64 bit) and curiously with an older version of the addon it overrode the new tab to a custom local url of my choosing, until the addon suddenly updated and now "restrictions" prevent it. Reverting to an older version of the addon (6.0.1, in my case) fixed the issue. the addon overrides new tabs with local URL's with ease. If you're like my and have a custom home page you made, use an older version of the addon and it will work. Worked for me, anyway. Thanks.

**Comment by cadeyrn** [comment]
> is not at all true

It's true and I don't think that you know that better than the developer of the add-on. It's not possible for WebExtensions, period.

**Comment by Angolmagyar** [comment]
I don't claim to know better than the developers, but if it did in fact work by using an older version, then..... am I really wrong? I didn't mean to offend, I was just throwing something out there for people who have the same issue I had, as it might work for others too. It worked on my desktop and my laptop, so I imagine it would work for others, and that's why I said it wasn't true that due to firefox restrictions, local URL is no longer possible, because if simply by reverting the ADDON's version it did exactly that.

**Comment by cadeyrn** [comment]
New Tab Override was a legacy add-on until version 6.0. Since 7.0 New Tab Override is a WebExtension, that's a totally different add-on architecture and there are a lot of restrictions, at least for the moment. Starting with Firefox 57 only WebExtensions are supported by Firefox so it was necessary to re-revelop New Tab Override as WebExtension. Firefox Nightly is already on version 57. There is no way to access local files via URL for WebExtensions.
