### ISSUE TITLE
Request: Use Firefox Home Page and still have "Set focus to web page (search bar) instead of address bar

### ISSUE THREAD

**Issue by sweeks888** [cadeyrn/newtaboverride#342]
Currently if I choose to use the Firefox home page (to facilitate the use of shortcut tiles) instead of say the Google home page, the cursor focus goes back to the address bar, it doesn't matter if the Set focus... box is checked or not, the cursor focus moves back to the address bar.  Now if I choose Google (or any other page as home) the Set focus... box works as designed and always opens in the search box. 
Unfortunately Firefox home page doesn't actually have a URL to use, to set "custom URL" within the app, or I could just do this.  Kind of a Catch-22 here.
Is there a work around for this... so I can use the Firefox home page for my start up page and for all new tabs, and also have the focus of the cursor remain in the web page search box, where it belongs?

Thank you
Steve W.

**Comment by cadeyrn** [comment]
This makes no sense to me. If you want to use the default home page of Firefox, there is no need to use this add-on at all. And to set the focus to the search box of the default home page of Firefox doesn't make sense either as the focus will automatically switch to the address bar once you start typing something.

**Comment by sweeks888** [comment]
Exactly… and I was hoping there was a way to not have it automatically move to the address bar, that’s just idiotic in the first place.

I couldn’t find a way now to prevent this from happening, must be the way the wrote the script and the search box is just a fake box that actually does nothing, is that what I’m understanding?

 

Thank you

Steve W.

**Comment by cadeyrn** [comment]
> Exactly… and I was hoping there was a way to not have it automatically move to the address bar, that’s just idiotic in the first place.

This has nothing to do with New Tab Override at all. It's the behavior of Firefox. And no, that's not "idiotic" just because you don't like it.

> the search box is just a fake box that actually does nothing

It does something: it gives users who don't know that they can use the address bar directly for searching an entry point for searching the web. So it's more than a "fake box", it has an UX purpose.

**Comment by cadeyrn** [comment]
> Exactly… and I was hoping there was a way to not have it automatically move to the address bar, that’s just idiotic in the first place.

This has nothing to do with New Tab Override at all. It's the behavior of Firefox. And no, that's not "idiotic" just because you don't like it.

> the search box is just a fake box that actually does nothing

It does something: it gives users who don't know that they can use the address bar directly for searching an entry point for searching the web. So it's more than a "fake box", it has an UX purpose.

---

There is no point in setting the focus to the search field of the default home page, as the focus moves to the address bar anyway. Therefore, I will close this issue as neither useful nor possible.

**Comment by sweeks888** [comment]
Ok, thank you for getting back to me Sören, appreciate your time and now have a better understanding of what FF is dong with their home page and why what I want my home page to do isn’t possible in this manner.

 

Steve W.
