### ISSUE TITLE
local file, internal style is ignored

### ISSUE THREAD

**Issue by grepwold** [cadeyrn/newtaboverride#355]
I've set my homepage to open in each new tab and it's a local file.

The text is there but the internal style (a single <b>style="..."</b>
in the body tag) is not applied.  When I Ctrl-U to see the file source,
I see instead a page with three Javascript includes.  One is
"local_file.js" and this include apparently derives the local file
content using this line <code>const { local_file } = await
browser.storage.local.get({ local_file : defaults.local_file });</code>
and dynamically inserts it into the page.

Is there a way to apply a simple style to a local file, or does this
method of including the text not allow it?

**Comment by grepwold** [comment]
I see you've added this to somewhat similar reports _Please start a local server for complex local files, as explained in the extension. Then you don't have any restrictions at all._
To explain, the URL **is** served by a local server - though a very rudimentary one.

_as explained in the extension_ can you explain where I find this?

**Comment by cadeyrn** [comment]
> To explain, the URL is served by a local server

Are you sure? Because then you wouldn't use the local file option and upload a file. Instead, you would use the default option for a custom URL and enter the URL of the local server, for example https://localhost/your_file.html. This way, there are no restrictions for local files.

> as explained in the extension can you explain where I find this?

If you select the option for a local file, there is a long text directly below it explaining that you can use XAMPP or MAMP, for example.

**Comment by grepwold** [comment]
Sorry, you're quite right.  I got completely confused between two installations.

I'll need to recheck when I'm next at the other one.  Please close this and thank you for your quick response and your useful plugins.
