### ISSUE TITLE
Select URL when focus is set to address bar on new tab

### ISSUE THREAD

**Issue by Sadsurfer** [cadeyrn/newtaboverride#44]
Hey,
Great addon - liking it.
One feature request if I may.

It would be great to select the URL in the address bar when the focus option is enabled so that you can start to type straight away and not have to manual select the URL in the address bar beforehand.

Hopefully that makes sense!

**Comment by cadeyrn** [comment]
Hi,

yes, it makes a lot of sense, but unfortunately it's not possible for WebExtensions at the moment. It will be possible in the future, but in Firefox 57 at the earliest.

I'll close this ticket because it's a WebExtension restriction and I can't do anything now but it will definitively be fixed once it will be possible. It's a permanent item on my todo list to check the current state of this.
