### ISSUE TITLE
Loads from newtab.html should probably replace history

### ISSUE THREAD

**Issue by bzbarsky** [cadeyrn/newtaboverride#46]
STEPS TO REPRODUCE:

1.  Set up new tab override in Firefox nightly to use "about:blank" for new tabs.
2. Open a new tab.
3. Hit the back button.

ACTUAL RESULT: URL bar shows moz-extension://b084e050-67f5-fc42-bf94-7d9e231067d5/html/newtab.html

EXPECTED RESULT: Back button is not even enabled; can't navigate back from the about:blank the new tab opens.

DETAILS: It looks like the addon uses tabs.update() to load about:blank.  I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1397383 on being able to use that to do a history-replacing load, but it may be worth checking whether location.replace() does the right thing here too...

**Comment by cadeyrn** [comment]
Hi,

thank you for your report. Unfortunately using window.location.replace(url) does not work for me, it has the same result as browser.tabs.update(), the back button is enabled. I'll see how useful bug 1397383 will be (thanks for filing!), maybe this will be the solution.

If it doesn't help I'll remove the newtab.html entry from the history. It's not a nice solution since it requires an additional permission but it's currently implemented in the development version [1] and it works. 

[1] https://github.com/cadeyrn/newtaboverride/blob/49ebd5d79ea852b8ae52d7a833676be1dab30955/src/js/newtab.js#L77

**Comment by cadeyrn** [comment]
Will be fixed in New Tab Override 9.0.

By the way: the new loadReplace option for browser.tabs.update() works for disabling the back button, but I still have to browser.history.deleteUrl() because even with loadReplace:true there is a entry in the history.

**Comment by cadeyrn** [comment]
It's part of New Tab Override 9.0, released a few minutes ago.
