### ISSUE TITLE
Can't get focus set to search field in Google, FF 55.0.3 

### ISSUE THREAD

**Issue by Bill-IT** [cadeyrn/newtaboverride#48]
Ever since FF 55 was installed, I have been unable to set focus to search field on http://www.google.com.

**Comment by cadeyrn** [comment]
There is an option to focus the website (what means the search field will get the focus). If it doesn't work for you please try without other add-ons enabled. In a clean Firefox the option works.

By the way, you should use https://www.google.com (https instead of http), otherwise you will be redirected to https and a redirect costs time.

**Comment by Bill-IT** [comment]
Thanks. Yes, that did work after I disabled other add-ons AND reloaded FF.

**Comment by cadeyrn** [comment]
So there seems to be a conflict with another add-on. You could try enabling one add-on, test again, then enabling the next one and so on until you have found the cause.
