### ISSUE TITLE
items appearing in about:debugging

### ISSUE THREAD

**Issue by grauenwolfe** [cadeyrn/newtaboverride#80]
Seeing this in about:debugging. Haven't seen anything there before so I'm not sure what it is. Anything of concern?

![debugging-nto](https://user-images.githubusercontent.com/25858089/32128783-75b47872-bb46-11e7-811f-005c8f99148d.png)

**Comment by grauenwolfe** [comment]
Nevermind. Got it clearup up.

**Comment by cadeyrn** [comment]
Hi,

there is a simple explanation: The warning appears on Firefox 56 but not in Firefox 57 because of a permission which is only available on Firefox 57 and higher. The permission is needed to support a feature of New Tab Override for users of Firefox 57 and higher. Firefox 56 ignores this permission but shows a warning in about:debugging.

**Comment by grauenwolfe** [comment]
Hey Sören, your answer is exactly right. I should have maybe explained this when I closed this issue. However, there is a solution in FF v56. NTO's UUID can be added manually the exceptions list. I had to do the same thing with uBlock Origin as well. Screenshot below showing about:debugging after adding `moz-extension://f07b76d5-25a9-7945-9cc4-302fc1d0616f` to my exceptions list.

Thanks. Love this extension, hate that it even has to exist though.

![screen](https://user-images.githubusercontent.com/25858089/32140318-4514b246-bc2b-11e7-8ea7-ba0b31b38c02.png)
